In [1]:
import pandas as pd

In [3]:
import warnings
import pandas as pd
import glob
import os

pd.options.display.float_format = '{:,.0f}'.format
warnings.filterwarnings('ignore')

In [4]:
bayareafips_full = {'06001': 'Alameda',
                    '06013': 'Contra Costa',
                    '06041': 'Marin',
                    '06055': 'Napa',
                    '06075': 'San Francisco',
                    '06081': 'San Mateo',
                    '06085': 'Santa Clara',
                    '06097': 'Sonoma',
                    '06095': 'Solano'}

In [299]:
race_map = {1: 'White, Non-Hispanic',
            2: 'Black, Non-Hispanic',
            3: 'American Indian or Alaska Native, Non-Hispanic',
            4: 'Asian, Non-Hispanic',
            5: 'Native Hawaiian or Pacific Islander, Non-Hispanic',
            6: 'Multiracial (two or more of above races), Non-Hispanic',
            7: 'Hispanic (any race)'}
race_map_remi = {1: 'White-NonHispanic',
            2: 'Black-NonHispanic',
            3: 'Other-NonHispanic',
            4: 'Other-NonHispanic',
            5: 'Other-NonHispanic',
            6: 'Other-NonHispanic',
            7: 'Hispanic'}

In [5]:
cog_regions = {'06001': 'ABAG/MTC',
               '06013': 'ABAG/MTC',
               '06041': 'ABAG/MTC',
               # '06053': 'AMBAG',
               '06055': 'ABAG/MTC',
               # '06069': 'AMBAG',
               '06075': 'ABAG/MTC',
               '06073': 'SANDAG',
               '06081': 'ABAG/MTC',
               '06085': 'ABAG/MTC',
               # '06087': 'AMBAG',
               '06095': 'ABAG/MTC',
               '06097': 'ABAG/MTC',
               # '06077': 'SJCOG',
               # '06099': 'STANCOG',
               # '06047': 'MCAG',
               '06025': 'SCAG',  # imperial
               '06037': 'SCAG',   # LA
               '06071': 'SCAG',  # san bernadino
               '06059': 'SCAG',  # orange
               '06065': 'SCAG',  # riverside
               '06111': 'SCAG',  # ventura
               '06067': 'SACOG',  # 'yolo'
               '06101': 'SACOG',  # 'sutter'
               '06113': 'SACOG',  # 'yolo'
               '06115': 'SACOG'
               }

cog_regions

{'06001': 'ABAG/MTC',
 '06013': 'ABAG/MTC',
 '06041': 'ABAG/MTC',
 '06055': 'ABAG/MTC',
 '06075': 'ABAG/MTC',
 '06073': 'SANDAG',
 '06081': 'ABAG/MTC',
 '06085': 'ABAG/MTC',
 '06095': 'ABAG/MTC',
 '06097': 'ABAG/MTC',
 '06025': 'SCAG',
 '06037': 'SCAG',
 '06071': 'SCAG',
 '06059': 'SCAG',
 '06065': 'SCAG',
 '06111': 'SCAG',
 '06067': 'SACOG',
 '06101': 'SACOG',
 '06113': 'SACOG',
 '06115': 'SACOG'}

In [228]:

ca_counties
# bin_year = [0,1850,1900,1920,1940,1960,1980,2000,2020,2040]
# bin_year = [0]+list(range(1860,2041,10))

# bin_year = [0]+list(range(1860,2041,20))

        County Name  FIPS Code  bayarea STCOUNTY           county
0           ALAMEDA          1        1    06001          Alameda
1            ALPINE          3      NaN    06003           Alpine
2            AMADOR          5      NaN    06005           Amador
3             BUTTE          7      NaN    06007            Butte
4         CALAVERAS          9      NaN    06009        Calaveras
5            COLUSA         11      NaN    06011           Colusa
6      CONTRA COSTA         13        1    06013     Contra Costa
7         DEL NORTE         15      NaN    06015        Del Norte
8         EL DORADO         17      NaN    06017        El Dorado
9            FRESNO         19      NaN    06019           Fresno
10            GLENN         21      NaN    06021            Glenn
11         HUMBOLDT         23      NaN    06023         Humboldt
12         IMPERIAL         25      NaN    06025         Imperial
13             INYO         27      NaN    06027             Inyo
14             KERN         29      NaN    06029             Kern
15            KINGS         31      NaN    06031            Kings
16             LAKE         33      NaN    06033             Lake
17           LASSEN         35      NaN    06035           Lassen
18      LOS ANGELES         37      NaN    06037      Los Angeles
19           MADERA         39      NaN    06039           Madera
20            MARIN         41        1    06041            Marin
21         MARIPOSA         43      NaN    06043         Mariposa
22        MENDOCINO         45      NaN    06045        Mendocino
23           MERCED         47      NaN    06047           Merced
24            MODOC         49      NaN    06049            Modoc
25             MONO         51      NaN    06051             Mono
26         MONTEREY         53      NaN    06053         Monterey
27             NAPA         55        1    06055             Napa
28           NEVADA         57      NaN    06057           Nevada
29           ORANGE         59      NaN    06059           Orange
30           PLACER         61      NaN    06061           Placer
31           PLUMAS         63      NaN    06063           Plumas
32        RIVERSIDE         65      NaN    06065        Riverside
33       SACRAMENTO         67      NaN    06067       Sacramento
34       SAN BENITO         69      NaN    06069       San Benito
35   SAN BERNARDINO         71      NaN    06071   San Bernardino
36        SAN DIEGO         73      NaN    06073        San Diego
37    SAN FRANCISCO         75        1    06075    San Francisco
38      SAN JOAQUIN         77      NaN    06077      San Joaquin
39  SAN LUIS OBISPO         79      NaN    06079  San Luis Obispo
40        SAN MATEO         81        1    06081        San Mateo
41    SANTA BARBARA         83      NaN    06083    Santa Barbara
42      SANTA CLARA         85        1    06085      Santa Clara
43       SANTA CRUZ         87      NaN    06087       Santa Cruz
44           SHASTA         89      NaN    06089           Shasta
45           SIERRA         91      NaN    06091           Sierra
46         SISKIYOU         93      NaN    06093         Siskiyou
47           SOLANO         95        1    06095           Solano
48           SONOMA         97        1    06097           Sonoma
49       STANISLAUS         99      NaN    06099       Stanislaus
50           SUTTER        101      NaN    06101           Sutter
51           TEHAMA        103      NaN    06103           Tehama
52          TRINITY        105      NaN    06105          Trinity
53           TULARE        107      NaN    06107           Tulare
54         TUOLUMNE        109      NaN    06109         Tuolumne
55          VENTURA        111      NaN    06111          Ventura
56             YOLO        113      NaN    06113             Yolo
57             YUBA        115      NaN    06115             Yuba

In [ ]:
def generate_labels(bin_year,pre_string,post_string,suffix=None):
    # Add 0 at the beginning of the breakpoints list
    #bin_year = [0] + bin_year
    
    # Generate labels for each bin
    labels = [f'{a} to {b-1}' for a, b in zip(bin_year[:-1], bin_year[1:])]
    
    # Modify the first and last labels
    labels[0] = f'{pre_string}{bin_year[1]}'
    labels[-1] = f'{post_string}{bin_year[-2]}'
    
    # Add the optional suffix to the last label if provided
    if suffix:
        for i, lab in enumerate(labels):
            newlab = f'{lab} {suffix}'
            labels[i] = newlab 
        
        #labels[-1] += f' {suffix}'
    
    # Return the list of labels
    return labels

In [160]:
bin_age = list(range(0, 86, 5)) + [111]
labels_age = generate_labels(bin_age,'under ','More than ',suffix='years')
labels_age[-1] = '85 years and over'
labels_age

In [282]:
bin_year = list(range(1960, 2061, 10))
labels_year = generate_labels(bin_year,'Before ','After ')
labels_year

['Before 1970',
 '1970 to 1979',
 '1980 to 1989',
 '1990 to 1999',
 '2000 to 2009',
 '2010 to 2019',
 '2020 to 2029',
 '2030 to 2039',
 '2040 to 2049',
 'After 2050']

In [283]:
ca_counties = pd.read_csv('/Users/aolsen/Box/Modeling and Surveys/Projects/Regional Growth Forecast Update/Forecasts/ca_county_fips.csv',sep="\t")
ca_counties['STCOUNTY'] = ca_counties['FIPS Code'].apply(lambda x: f'06{x:03d}')
ca_counties['county'] = ca_counties['County Name'].str.title()

In [284]:
years_5 = range(2010, 2051, 5)

# Load DOF data

In [285]:
dof = pd.read_csv('/Users/aolsen/Box/Modeling and Surveys/Projects/Regional Growth Forecast Update/Forecasts/DOF - Population Forecast/P3_Complete.csv')

In [288]:
dof['STCOUNTY'] = dof.fips.apply(lambda x: f'{x:05d}')
dof['cog_region'] = dof.STCOUNTY.map(cog_regions)

dof['cog_region'] = dof['cog_region'].fillna('Other COG')
dof['county'] = dof.STCOUNTY.map(ca_counties.set_index('STCOUNTY').county)
dof['value'] = dof.perwt

In [300]:
dof['race_ethn'] = dof.race7.map(race_map_remi)

In [301]:
dof['age_bin'] = pd.cut(dof.agerc, bins=bin_age,
                        labels=labels_age, include_lowest=True,
                        right=False)
dof.groupby(['age_bin', 'agerc'], observed=True).size().head(17)

age_bin         agerc
under 5 years   0        41412
                1        41412
                2        41412
                3        41412
                4        41412
5 to 9 years    5        41412
                6        41412
                7        41412
                8        41412
                9        41412
10 to 14 years  10       41412
                11       41412
                12       41412
                13       41412
                14       41412
15 to 19 years  15       41412
                16       41412
dtype: int64

# Summaries

In [317]:
wb = pd.ExcelWriter('/Users/aolsen/Box/Modeling and Surveys/Projects/Regional Growth Forecast Update/Forecasts/harvested/dof_summary.xlsx')

In [318]:
summary_by_yr_cnty_race = dof.groupby(['year','cog_region','county','race_ethn'],observed=True).value.sum().reset_index()
summary_by_yr_cnty_race.to_excel(wb,'summary_by_yr_cnty_race')

In [319]:
summary_by_yr_cnty = dof.groupby(['year','county'],observed=True).value.sum().reset_index()
summary_by_yr_cnty.to_excel(wb,'summary_by_yr_cnty')

In [320]:
summary_by_yr_cnty = dof.groupby(['year','county'],observed=True).value.sum().reset_index()
summary_by_yr_cnty.to_excel(wb,'summary_by_yr_cnty')

In [321]:
summary_by_yr_cnty_age = dof.groupby(['year','cog_region','county','age_bin'],observed=True).value.sum().reset_index()
summary_by_yr_cnty_age.to_excel(wb,'summary_by_yr_cnty_age')

In [322]:
#summary_by_yr_cnty_age.to_excel(wb,'summary_by_yr_cnty_age')

In [323]:
wb.close()

In [309]:
labels_age

['under 5 years',
 '5 to 9 years',
 '10 to 14 years',
 '15 to 19 years',
 '20 to 24 years',
 '25 to 29 years',
 '30 to 34 years',
 '35 to 39 years',
 '40 to 44 years',
 '45 to 49 years',
 '50 to 54 years',
 '55 to 59 years',
 '60 to 64 years',
 '65 to 69 years',
 '70 to 74 years',
 '75 to 79 years',
 '80 to 84 years',
 '85 years and over']